Squashed commit of the following:
commit 3b66c4e2943628da0af1057f7c8e9b3e064a8240
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Wed May 29 15:40:11 2024 -0600

    Return a dict for get_slots

commit d43638846693a2fd56721f70d40cd3d905903dfe
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Wed May 29 14:02:45 2024 -0600

    Add comments, typing

commit bd9c59e4e1925b1926adf79cec44ec39f16dc324
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Wed May 29 13:46:00 2024 -0600

    Rework Faction for easier consumption of API data

commit e431408cc59a27d42fef981dc5898353b497541b
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Wed May 29 12:15:51 2024 -0600

    Rename and correct typing

commit 9c13d421c13fbff3309cd530bf1df068546f74f8
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Tue May 28 14:43:32 2024 -0600

    Fix typo

commit ab2e1a0bf66f61d7d5eeebc42653d545c6b1370a
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Tue May 28 13:41:20 2024 -0600

    Don't include `self` in API documentation

commit c0500b77318892bf5a9c8372b35d698a5c13715b
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Tue May 28 13:41:09 2024 -0600

    Remove unused file

commit 6839794ac69d5dc4d8dbdf2789375b03a7defc33
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Tue May 28 12:48:28 2024 -0600

    Rename do_reconnect_gameserver to reconnect_gameserver

commit dfe1f95cc21cb5d9436d0e6b61bfa12a9390ce20
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Tue May 28 12:31:58 2024 -0600

    Install dependencies in one go

commit baab261e7f2705c8b261bd6ff0f931cd9a3c530c
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Tue May 28 12:12:16 2024 -0600

    Update compose file for running the backend/frontend dev servers

commit f971d863f3407a509277630f64aceb08c18c0760
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Tue May 28 12:11:43 2024 -0600

    Reduce disk utilization

commit a5e6cac941d2617f17b87291a43a7143efe0b1dd
Merge: 2f5d6da edac694
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Tue May 28 11:49:56 2024 -0600

    Merge branch 'master' into feat/autosettings_all_rcon_methods

commit edac6941c5b74add631bdd3030653f0bbbccffcc
Author: ElGuillermo <66552553+ElGuillermo@users.noreply.github.com>
Date:   Tue May 28 19:34:43 2024 +0200

    Update README.md (#566)

commit 96808482ccd29bb1dbccdcc3c2553a38e25d0524
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Tue May 28 11:34:09 2024 -0600

    Bump sqlalchemy from 2.0.29 to 2.0.30 (#570)

    Bumps [sqlalchemy](https://github.com/sqlalchemy/sqlalchemy) from 2.0.29 to 2.0.30.
    - [Release notes](https://github.com/sqlalchemy/sqlalchemy/releases)
    - [Changelog](https://github.com/sqlalchemy/sqlalchemy/blob/main/CHANGES.rst)
    - [Commits](https://github.com/sqlalchemy/sqlalchemy/commits)

    ---
    updated-dependencies:
    - dependency-name: sqlalchemy
      dependency-type: direct:production
      update-type: version-update:semver-patch
    ...

    Signed-off-by: dependabot[bot] <support@github.com>
    Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

commit 3f59440c9d04928400a5709e30d321607d76d96d
Author: ExcuseMi <ExcuseMi@users.noreply.github.com>
Date:   Tue May 28 19:33:11 2024 +0200

    Fix error in log stream when server is idle (#565)

    Fixes
    TypeError: cannot unpack non-iterable NoneType object when server has be idle in the log stream.
    The scenario occurs when last_seen is None and the tail returns None

commit 21abeb6cb3bb7904e6b1289c170d947301459013
Author: Florian <florian.schmidt.welzow@t-online.de>
Date:   Tue May 28 19:32:26 2024 +0200

    Salvage stats when player reconnects (#568)

    Previously, when a player disconnects and then reconnects to the server
    the stats gained in the previous session where lost. The CRCON would
    always only save the 'higher' stats value to compensate this a bit, which
    was far from perfect.
    With this commit, the CRCON will try to salvage the previously gained stats
    and combine them after the round ended.

commit 33efff187819d54e943ab2c410c76bd14b140357
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Tue May 28 11:30:37 2024 -0600

    Bump rq from 1.16.1 to 1.16.2 (#569)

    Bumps [rq](https://github.com/rq/rq) from 1.16.1 to 1.16.2.
    - [Release notes](https://github.com/rq/rq/releases)
    - [Changelog](https://github.com/rq/rq/blob/master/CHANGES.md)
    - [Commits](https://github.com/rq/rq/compare/v1.16.1...v1.16.2)

    ---
    updated-dependencies:
    - dependency-name: rq
      dependency-type: direct:production
      update-type: version-update:semver-patch
    ...

    Signed-off-by: dependabot[bot] <support@github.com>
    Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

commit 094c4798279994fe443ae3d4137861a01ade6bff
Author: C. Eric Mathey <48801688+cemathey@users.noreply.github.com>
Date:   Tue May 28 11:29:08 2024 -0600

    Include player ID when kicking, can't retrieve it from the game server post kick (#573)

commit 3c7f255c766715d67c644c1f619c4ba4fccf1d69
Author: Florian <florian.schmidt.welzow@t-online.de>
Date:   Tue May 28 19:28:26 2024 +0200

    align max players of automod to documentation (#575)

    The documentation mentions max players in seeding automod to be
    exclusive, but the code handled it inclusive. This commit aligns the
    code to the documentation again.

commit 53731593decec51c55b37cdba54d62f02954feaf
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Tue May 28 11:28:00 2024 -0600

    Bump pytest from 8.1.1 to 8.2.1 (#577)

    Bumps [pytest](https://github.com/pytest-dev/pytest) from 8.1.1 to 8.2.1.
    - [Release notes](https://github.com/pytest-dev/pytest/releases)
    - [Changelog](https://github.com/pytest-dev/pytest/blob/main/CHANGELOG.rst)
    - [Commits](https://github.com/pytest-dev/pytest/compare/8.1.1...8.2.1)

    ---
    updated-dependencies:
    - dependency-name: pytest
      dependency-type: direct:development
      update-type: version-update:semver-minor
    ...

    Signed-off-by: dependabot[bot] <support@github.com>
    Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

commit 468607ee3107b6da2b059f627c76d5c3f114e62f
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Tue May 28 11:27:23 2024 -0600

    Bump requests from 2.31.0 to 2.32.2 (#579)

    Bumps [requests](https://github.com/psf/requests) from 2.31.0 to 2.32.2.
    - [Release notes](https://github.com/psf/requests/releases)
    - [Changelog](https://github.com/psf/requests/blob/main/HISTORY.md)
    - [Commits](https://github.com/psf/requests/compare/v2.31.0...v2.32.2)

    ---
    updated-dependencies:
    - dependency-name: requests
      dependency-type: direct:production
      update-type: version-update:semver-minor
    ...

    Signed-off-by: dependabot[bot] <support@github.com>
    Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

commit 2f5d6da0ece0a97ecf41e8d4210cd8b67d58917b
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Tue May 28 10:25:46 2024 -0600

    Support errors_as_json for InvalidKeysConfigurationError

commit 93ae6e63cd97f57cfe9764d821009c4875d28a08
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Tue May 28 10:15:14 2024 -0600

    Remove upload_vips and rename async_upload_vips

commit 40eb6937bd17c53add1ad009f139b3a55c0a36b8
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Tue May 28 09:53:02 2024 -0600

    Fix arguments for unwatch_player

commit cf0c5ad91899c632190eeea099d5601ef1f5c82a
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Tue May 28 09:38:57 2024 -0600

    Return unban_profanities and result as a bool and not str

commit edd40905479b8fd7be4a22915921d601c8689270
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Tue May 28 09:24:48 2024 -0600

    Return temp_ban and result as a bool and not str and add type hints

commit 847deccdedaeae1844e29449e45f2871a1256f6a
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Wed May 22 15:32:49 2024 -0600

    Return switch_player_now and  switch_player_on_death result as a bool and not str

commit d1103b53d7909071d0face696e52be44e8eee875
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Wed May 22 14:59:23 2024 -0600

    Refactor set_welcome_message

commit 6815ee6c386204c7e38d73d73d7264f78f63e55d
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Wed May 22 14:36:12 2024 -0600

    Accept set_votekick_thresholds threshold_pairs as a list of tuples

commit 6af7899c11935de35383b43e00f328f5c561bcaa
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Wed May 22 14:35:08 2024 -0600

    Return set_votekick_enabled result as a bool and not str

commit 4f8185a25eb079f499ebcbafb59642ea98299b30
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Wed May 22 14:06:14 2024 -0600

    Return set_vip_slots_num result as a bool and not str and change parameter name

commit 0621d6f503ef62b71d794d125403eecbd843ed5a
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Wed May 22 13:59:34 2024 -0600

    Return set_team_switch_cooldown result as a bool and not str

commit 08f76c1693fbfef173f0d8110c853032d4322fe9
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Wed May 22 13:19:40 2024 -0600

    Accept either lists of strings or dicts for StandardBroadcastMessages

commit 9de1b87652715ea408d5ea56fdb46e252dc231b3
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Wed May 22 11:37:21 2024 -0600

    Return set_queue_length result as a bool and not str and change parameter name

commit 1c3222115732b681513379acedca87b90fb24d66
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Wed May 22 11:27:55 2024 -0600

    Remove set_name it was already moved to RconAPI as set_server_name

commit 8f42a994832ac7f712844270bb6ca2b1775318eb
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Wed May 22 11:15:12 2024 -0600

    Return set_max_ping_autokick result as a bool and not str

commit 0a6d9b0ea54fc9f25fb465c9212a98816cf90fea
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Wed May 22 11:11:10 2024 -0600

    Rename set_map_votemap_whitelist to set_votemap_whitelist and standardize parameter name

commit ae4c268a5e34114c5c67da994789536ddb12f94f
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Wed May 22 10:20:28 2024 -0600

    Move user config error conversion (str or JSON) to the API exposure level

commit 9ab90ac8c66db8e02843cb25b24b287ac609060a
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Tue May 21 16:31:13 2024 -0600

    Return set_idle_autokick_time result as a bool and not str

commit 71eb083a9969b232a787b4e4fed9d1c65c0a0016
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Tue May 21 16:00:24 2024 -0600

    Refactor set_broadcast

commit 82adedc4eb9b01b7a49bfec81d99c48738171168
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Tue May 21 15:04:19 2024 -0600

    Return set_autobalance_threshold result as a bool and not str

commit d88d9033aeed764071c0b875b77b21160901f8a8
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Tue May 21 14:54:13 2024 -0600

    Rename bool_ parameter to value

commit ef19f73ff52ab9856bddce6fbdf63ba4135ef6c3
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Tue May 21 14:26:54 2024 -0600

    Return set_autobalance_enabled result as a bool and not str

commit c2ab2c5d863edadd8fa7581fd6b36db859968af2
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Tue May 21 13:31:33 2024 -0600

    Bandaid AutoBroadcastUserConfig (accept both UI format as one string and the JSON format)

commit 2728724a86dfc3f78e933b16c4cde864da7f2022
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Tue May 21 13:13:49 2024 -0600

    Rename server_list endpoint get_server_list

commit f099fe20f6c3daf88efc81a812811047b94a756b
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Tue May 21 12:20:08 2024 -0600

    Return reset_votekick_thresholds result as a bool and not str

commit 074a82423503e745d29702c7222b86bf574e58a6
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Tue May 21 12:06:47 2024 -0600

    Return remove_vip result as a bool and not str

commit 897b0a8efd99ed65e893349c0d8c2aff4bc68fcc
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Tue May 21 11:57:47 2024 -0600

    Return results as boolean, accept player ID for perma ban and fix remove temp/perma ban due to receiving parsed banlogs not raw banlogs

commit e8d457f7edb1cf08f98e410ae294f6cd5003fb43
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Tue May 21 10:21:43 2024 -0600

    Return remove_all_vips result as a bool and not str

commit 2086c609b20fad3a5f960cb46a861b9136374e6d
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Tue May 21 10:19:58 2024 -0600

    Return command result for remove_map_from_rotation

commit 772f077f0b5e32178596e194a733f49499513053
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Tue May 21 09:54:43 2024 -0600

    Fix player count in browser page title

commit b3b707c9d586c0fb27aa8a533d6de2184688df7f
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Tue May 21 09:48:29 2024 -0600

    Fix player slots (current, max) usage

commit d1efa04b6e47291006524586ef34ccb51a2e42be
Author: C. Eric Mathey <emathey@protonmail.com>
Date:   Tue May 21 09:47:46 2024 -0600

    Return punish result as a bool and not str

commit aa75c92e85f4a40ff1e018b48d488db84a36bceb
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Mon Apr 29 10:19:17 2024 -0600

    Bump black from 24.4.0 to 24.4.2 (#562)

    Bumps [black](https://github.com/psf/black) from 24.4.0 to 24.4.2.
    - [Release notes](https://github.com/psf/black/releases)
    - [Changelog](https://github.com/psf/black/blob/main/CHANGES.md)
    - [Commits](https://github.com/psf/black/compare/24.4.0...24.4.2)

    ---
    updated-dependencies:
    - dependency-name: black
      dependency-type: direct:development
      update-type: version-update:semver-patch
    ...

    Signed-off-by: dependabot[bot] <support@github.com>
    Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

commit 36f9ac22fdfdedc8b7ad2a372c551beccb149c0d
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Mon Apr 29 10:14:14 2024 -0600

    Bump pydantic from 2.7.0 to 2.7.1 (#563)

    Bumps [pydantic](https://github.com/pydantic/pydantic) from 2.7.0 to 2.7.1.
    - [Release notes](https://github.com/pydantic/pydantic/releases)
    - [Changelog](https://github.com/pydantic/pydantic/blob/main/HISTORY.md)
    - [Commits](https://github.com/pydantic/pydantic/compare/v2.7.0...v2.7.1)

    ---
    updated-dependencies:
    - dependency-name: pydantic
      dependency-type: direct:production
      update-type: version-update:semver-patch
    ...

    Signed-off-by: dependabot[bot] <support@github.com>
    Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

commit 4d372327d34fa817c3943ce0e9428cc8cd974d7c
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Mon Apr 29 10:11:16 2024 -0600

    Bump redis from 5.0.3 to 5.0.4 (#564)

    Bumps [redis](https://github.com/redis/redis-py) from 5.0.3 to 5.0.4.
    - [Release notes](https://github.com/redis/redis-py/releases)
    - [Changelog](https://github.com/redis/redis-py/blob/master/CHANGES)
    - [Commits](https://github.com/redis/redis-py/compare/v5.0.3...v5.0.4)

    ---
    updated-dependencies:
    - dependency-name: redis
      dependency-type: direct:production
      update-type: version-update:semver-patch
    ...

    Signed-off-by: dependabot[bot] <support@github.com>
    Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

commit 2af20bf5bc635c57a119a1273630a1fab59c0ba6
Author: C. Eric Mathey <48801688+cemathey@users.noreply.github.com>
Date:   Fri Apr 26 11:59:07 2024 -0600

    Update map picture lookup (#560)

commit b21fbb85ead766f030965f85aede4dba8d1d6a43
Author: ElGuillermo <66552553+ElGuillermo@users.noreply.github.com>
Date:   Fri Apr 26 19:58:55 2024 +0200

    Update seeding_rules.py (#559)

    adding new skirmish maps

    Signed-off-by: ElGuillermo <66552553+ElGuillermo@users.noreply.github.com>