Fix error in log stream when server is idle (#565)
Fixes
TypeError: cannot unpack non-iterable NoneType object when server has be idle in the log stream.
The scenario occurs when last_seen is None and the tail returns None